version: "3"

services:
  app:
    container_name: app
    depends_on:
      - db
    build: .
    env_file:
      - .env
    environment:
      DB_HOST: db
    ports:
      - 3000:3000


  db:
    image: mysql
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - 3306:3306
    volumes:
      - ./mysql:/var/lib/mysql
